name: Build CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup requirements
      run: |
        sudo apt update
        sudo apt install libarchive-tools
    - name: make test
      run: make test
    - name: make
      run: make
    - name: remove .git
      run: rm -rf .git
    - name: Upload zip file to artifact
      uses: actions/upload-artifact@v4
      with:
          name: all
          path: ./
